/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matia
 */
public class Ventana extends javax.swing.JFrame {
    Gestor g;

    /**
     * Creates new form Ventana
     */
    public Ventana(Gestor g) {
        initComponents();
        this.setVisible(true);
        this.g=g;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSimular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIteraciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTiempoOcioso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad de Iteraciones");

        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reloj", "Evento", "RND", "T. Entre Llegadas", "Prox, Llegada", "RND", "Tipo", "RND", "Tiempo Atencion", "Fin Atencion", "Tiempo", "Fin Transmision", "RND", "T. Preparacion", "Fin Preparacion", "Estado", "Cola", "Tiempo en Mostrador", "Tiempo en Cocina", "Estado", "Tiempo Trabajando", "Tiempo Libre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIteracionesActionPerformed(evt);
            }
        });

        jLabel2.setText("Porcentaje de Tiempo Ocioso del Ayudante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimular))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTiempoOcioso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTiempoOcioso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnSimular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        this.g.limpiarVectores();
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setRowCount(0);
        for (int i = 0; i < Integer.parseInt(this.txtIteraciones.getText()); i++) {
            this.g.newVectorActual();
            this.addRowToJTable();
        }
        this.txtTiempoOcioso.setText(Double.toString(this.g.getTiempoOcioso()));
              
    }//GEN-LAST:event_btnSimularActionPerformed

    private void txtIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIteracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIteracionesActionPerformed

    /**
     * @param args the command line arguments
     */


        public void addRowToJTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        ArrayList list =this.g.crearArrayList();
        Object rowData[] = new Object[22];

            
            rowData[0]=list.get(0);
            rowData[1]=list.get(1);
            rowData[2]=list.get(2);
            rowData[3]=list.get(3);
            rowData[4]=list.get(4);
            rowData[5]=list.get(5);
            rowData[6]=list.get(6);
            rowData[7]=list.get(7);
            rowData[8]=list.get(8);
            rowData[9]=list.get(9);
            rowData[10]=list.get(10);
            rowData[11]=list.get(11);
            rowData[12]=list.get(12);
            rowData[13]=list.get(13);
            rowData[14]=list.get(14);
            rowData[15]=list.get(15);
            rowData[16]=list.get(16);
            rowData[17]=list.get(17);
            rowData[18]=list.get(18);
            rowData[19]=list.get(19);
            rowData[20]=list.get(20);
            rowData[21]=list.get(21);
            
            
                        

            
            model.addRow(rowData);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIteraciones;
    private javax.swing.JTextField txtTiempoOcioso;
    // End of variables declaration//GEN-END:variables
}
