/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matia
 */
public class Ventana extends javax.swing.JFrame {
    Gestor g;

    /**
     * Creates new form Ventana
     */
    public Ventana(Gestor g) {
        initComponents();
        this.setVisible(true);
        this.g=g;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSimular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIteraciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTiempoOcioso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPorcentajeTiempoCocina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTiempoEnMostrador = new javax.swing.JTextField();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        btnSimularRaro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad de Iteraciones");

        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reloj", "Evento", "RND", "T. Entre Llegadas", "Prox, Llegada", "RND", "Tipo", "RND", "Tiempo Atencion", "Fin Atencion", "Tiempo", "Fin Transmision", "RND", "T. Preparacion", "Fin Preparacion", "Estado", "Cola", "Tiempo en Mostrador", "Tiempo en Cocina", "Estado", "Tiempo Trabajando", "Tiempo Libre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIteracionesActionPerformed(evt);
            }
        });

        jLabel2.setText("Porcentaje de Tiempo Ocioso del Ayudante");

        jLabel3.setText("Porcentaje de Tiempo en Cocina del Jefe");

        txtPorcentajeTiempoCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeTiempoCocinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Porcentaje de Tiempo en Mostrador del Jefe");

        txtDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesdeActionPerformed(evt);
            }
        });

        txtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHastaActionPerformed(evt);
            }
        });

        btnSimularRaro.setText("Simular");
        btnSimularRaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularRaroActionPerformed(evt);
            }
        });

        jLabel5.setText("Desde");

        jLabel6.setText("Hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTiempoEnMostrador)
                            .addComponent(txtTiempoOcioso)
                            .addComponent(txtPorcentajeTiempoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1301, Short.MAX_VALUE)
                        .addComponent(btnSimular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtDesde))
                        .addGap(18, 18, 18)
                        .addComponent(btnSimularRaro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimularRaro)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSimular)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTiempoOcioso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPorcentajeTiempoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTiempoEnMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        this.g.limpiarVectores();
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setRowCount(0);
        for (int i = 0; i < Integer.parseInt(this.txtIteraciones.getText()); i++) {
            this.g.newVectorActual();
            this.addRowToJTable();
        }
        
        this.txtTiempoOcioso.setText(Double.toString(this.g.calcularPorcentajeOcioso()));

        this.txtPorcentajeTiempoCocina.setText(Double.toString(this.g.calcularPorcentajeEnCocina()));
        this.txtTiempoEnMostrador.setText(Double.toString(100- this.g.calcularPorcentajeEnCocina()));
              
    }//GEN-LAST:event_btnSimularActionPerformed

    private void txtIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIteracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIteracionesActionPerformed

    private void txtPorcentajeTiempoCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeTiempoCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeTiempoCocinaActionPerformed

    private void txtDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesdeActionPerformed

    private void txtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHastaActionPerformed

    private void btnSimularRaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularRaroActionPerformed

                this.g.limpiarVectores();
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setRowCount(0);
        for (int i = 0; i < Integer.parseInt(this.txtIteraciones.getText()); i++) {
            this.g.newVectorActual();
            if (Integer.parseInt(this.txtDesde.getText())<=i && i<=Integer.parseInt(this.txtHasta.getText())) 
            {
            this.addRowToJTable();
            }

        }
        
        this.txtTiempoOcioso.setText(Double.toString(this.g.calcularPorcentajeOcioso()));

        this.txtPorcentajeTiempoCocina.setText(Double.toString(this.g.calcularPorcentajeEnCocina()));
        this.txtTiempoEnMostrador.setText(Double.toString(100- this.g.calcularPorcentajeEnCocina()));
    }//GEN-LAST:event_btnSimularRaroActionPerformed

    /**
     * @param args the command line arguments
     */


        public void addRowToJTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        ArrayList list =this.g.crearArrayList();
        Object rowData[] = new Object[22];

            
            rowData[0]=list.get(0);
            rowData[1]=list.get(1);
            rowData[2]=list.get(2);
            rowData[3]=list.get(3);
            rowData[4]=list.get(4);
            rowData[5]=list.get(5);
            rowData[6]=list.get(6);
            rowData[7]=list.get(7);
            rowData[8]=list.get(8);
            rowData[9]=list.get(9);
            rowData[10]=list.get(10);
            rowData[11]=list.get(11);
            rowData[12]=list.get(12);
            rowData[13]=list.get(13);
            rowData[14]=list.get(14);
            rowData[15]=list.get(15);
            rowData[16]=list.get(16);
            rowData[17]=list.get(17);
            rowData[18]=list.get(18);
            rowData[19]=list.get(19);
            rowData[20]=list.get(20);
            rowData[21]=list.get(21);
            
            
                        

            
            model.addRow(rowData);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JButton btnSimularRaro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtIteraciones;
    private javax.swing.JTextField txtPorcentajeTiempoCocina;
    private javax.swing.JTextField txtTiempoEnMostrador;
    private javax.swing.JTextField txtTiempoOcioso;
    // End of variables declaration//GEN-END:variables
}
